
[Upstream_Noise]
	#Maximum Noise Threshold for generation. Cannot be less than MinThreshold
	#Range: -1000.0 ~ 1000.0
	MaxThreshold = 5.8
	#How frequent rivers curve.
	#Range: -1000.0 ~ 1000.0
	CurvingFrequency = 0.010
	#River curving multiplier.
	#Range: 0.0 ~ 1000.0
	CurvingMultiplier = 0.8
	#How spread out rivers generate.
	#Range: -1000.0 ~ 1000.0
	RiverSpread = 0.001
	#Minimum Noise Threshold for generation. Cannot be greater than MaxThreshold
	#Range: -1000.0 ~ 1000.0
	MinThreshold = 5.591
	#Print the lowest and highest noise values in latest.log?
	#Useful for getting the range for Min & Max thresholds.
	PrintLatestLog = false
	#Generate Vanilla Rivers?
	VanillaRivers = false

